apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
spec:
  selector:
    matchLabels:
      app: counter-service
  replicas: 3
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
        - name: counter-service
          image: tfrisz/counter-service:latest
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: http
              containerPort: 80